### ISSUE TITLE
Careers page link styling

### ISSUE THREAD

**Issue by rationaledesign** [joshuarule/mainspringenergy.com#110]
LInk here should be medium weight
<img width="680" alt="Screen Shot 2021-02-01 at 10 47 09 PM" src="https://user-images.githubusercontent.com/6684700/106568955-d2fe3f00-64e8-11eb-958d-9d0221099c89.png">

**Comment by rationaledesign** [comment]
At top of the page, link should be medium as well, like so:
<img width="988" alt="Screen Shot 2021-02-01 at 11 55 32 PM" src="https://user-images.githubusercontent.com/6684700/106569149-093bbe80-64e9-11eb-8952-3b54c74731a9.png">


Currently,  it seems to be bold:
![Uploading Screen Shot 2021-02-01 at 10.47.02 PM.png…]()


Finally – something seems off between the spacing /sizing of the body copy and space to the next paragraph. What might be happening? (See above images)

**Comment by joshuarule** [comment]
@rationaledesign looks like there is an extra space in the CMS for that paragraph space
