### ISSUE TITLE
Footer contact link resolve

### ISSUE THREAD

**Issue by rationaledesign** [joshuarule/mainspringenergy.com#116]
Footer "Contact" link should launch mailto: for info@mainspringenergy.com
<img width="159" alt="Screen Shot 2021-02-01 at 10 46 33 PM" src="https://user-images.githubusercontent.com/6684700/106570546-e0b4c400-64ea-11eb-8905-77eb4a1722d6.png">

**Comment by joshuarule** [comment]
@rationaledesign are you sure on this one? They already have an email on the footer.

**Comment by rationaledesign** [comment]
Let's confirm w/ Maria

Otherwise, we could put them to the contact form, but that doesn't make sense as they might not be a B2B customer. 

Maybe we kill it?
