### ISSUE TITLE
General – Footer color + bleed adjust

### ISSUE THREAD

**Issue by rationaledesign** [joshuarule/mainspringenergy.com#12]
<img width="1502" alt="Screen Shot 2021-01-18 at 6 37 42 PM" src="https://user-images.githubusercontent.com/6684700/104993102-31023100-59d7-11eb-916e-f123217d80fa.png">
Footer color should be F9F4EC

also, footer color fill should extend to the bottom of the page w/ a single spacing unit (G) underneath (120 px on desktop) from the content to page bottom.

**Comment by joshuarule** [comment]
as the content gets filled out the space below the footer will get fixed. changed the color

**Comment by rationaledesign** [comment]
Sounds good
