### ISSUE TITLE
Increase spacing between solutions sub-sections

### ISSUE THREAD

**Issue by rationaledesign** [joshuarule/mainspringenergy.com#125]
![image](https://user-images.githubusercontent.com/6684700/106835801-d01c5f00-664c-11eb-9ff6-53ba376f6651.png)

Spacing between these sections (marked yellow), should each be set to 
<img width="690" alt="Screen Shot 2021-02-03 at 6 24 43 PM" src="https://user-images.githubusercontent.com/6684700/106835974-1ffb2600-664d-11eb-8821-ab25180e80d9.png">
spacing unit "G"

**Comment by joshuarule** [comment]
set section id and add custom spacing for the CTAs
