### ISSUE TITLE
Text aliasing

### ISSUE THREAD

**Issue by rationaledesign** [joshuarule/mainspringenergy.com#126]
Are we using "greyscale" or "sub-pixel"?

https://www.html5rocks.com/en/tutorials/internals/antialiasing-101/

**Comment by rationaledesign** [comment]
Or is this a font smoothing issue?
https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth

**Comment by rationaledesign** [comment]
Example:

Should look like this:
<img width="1345" alt="Screen Shot 2021-02-03 at 6 32 46 PM" src="https://user-
images.githubusercontent.com/6684700/106837336-4f129700-664f-11eb-8aaa-475a680df9c9.png">

Looks like this:
<img width="1221" alt="Screen Shot 2021-02-03 at 6 33 16 PM" src="https://user-images.githubusercontent.com/6684700/106837449-589bff00-664f-11eb-9819-638a97d43b4a.png">


![image](https://user-images.githubusercontent.com/6684700/106837502-736e7380-664f-11eb-8d65-f44e361933bc.png)

**Comment by joshuarule** [comment]
<img width="344" alt="image" src="https://user-images.githubusercontent.com/1295819/106910348-2336f600-66cf-11eb-9713-2ed446144faa.png">
It's using font smoothing...but as I have mentioned before Chrome doesn't honor these settings.
