### ISSUE TITLE
General – Fonts looks too heavy

### ISSUE THREAD

**Issue by rationaledesign** [joshuarule/mainspringenergy.com#14]
Is this a greyscale aliasing thing? Aliasing off?
Forget how we had to solve this on every site. 

For example, Sketch on top, Safari on the bottom (Chrome looks the same).... top looks good, the bottom is too heavy: 
<img width="1344" alt="Screen Shot 2021-01-19 at 8 45 08 AM" src="https://user-images.githubusercontent.com/6684700/105065675-f8904080-5a32-11eb-8161-4c047925b72a.png">

**Comment by joshuarule** [comment]
@rationaledesign added font-smoothing which affects only webkit browsers like safari and firefox. I'm not sure there is anything to thin out the fonts on chrome.
