### ISSUE TITLE
Solutions – mobile spacing on section

### ISSUE THREAD

**Issue by rationaledesign** [joshuarule/mainspringenergy.com#144]
Can we split this spacing in half (in red) on this breakpoint only right here?

![misc – close up spacing by half on mobile here – IMG_2620](https://user-images.githubusercontent.com/6684700/107129504-9c268100-687a-11eb-93ff-2e4d61c05828.PNG)

**Comment by joshuarule** [comment]
if text-columns only have one column then no margin bottom on the column
