### ISSUE TITLE
Navigation – not floating on scroll up on mobile

### ISSUE THREAD

**Issue by rationaledesign** [joshuarule/mainspringenergy.com#145]
No floating nav on mobile....
![mobile nav floating – IMG_2650](https://user-images.githubusercontent.com/6684700/107129966-30461780-687e-11eb-8f27-55cd0119b069.PNG)

**Comment by joshuarule** [comment]
@rationaledesign I don't see this on my end. Send a video if you can.

**Comment by joshuarule** [comment]
@rationaledesign is this still a thing?
