### ISSUE TITLE
Company – Remove selected outline person selected state

### ISSUE THREAD

**Issue by rationaledesign** [joshuarule/mainspringenergy.com#155]
Not sure if this is really an issue or just a quirk I had. Noticed in Chrome some exects staying "highlighted" w/ this box (Accessibility
<img width="617" alt="box issue" src="https://user-images.githubusercontent.com/6684700/107131658-57581580-688d-11eb-8f04-a76c8e8bd75f.png">
 thing?) when clicking:

**Comment by joshuarule** [comment]
@rationaledesign We can remove that. Changing issue title
