### ISSUE TITLE
Mobile hover issue, stuck for advancing

### ISSUE THREAD

**Issue by rationaledesign** [joshuarule/mainspringenergy.com#166]
https://user-images.githubusercontent.com/6684700/108134372-f7baf080-706a-11eb-8b70-29fe1ba1e79c.MP4

https://user-images.githubusercontent.com/6684700/108134389-ff7a9500-706a-11eb-8599-fb1cb56e45d9.MP4

**Comment by joshuarule** [comment]
Closing until we can repro
