### ISSUE TITLE
Tech white papers missing

### ISSUE THREAD

**Issue by rationaledesign** [joshuarule/mainspringenergy.com#188]
<img width="1458" alt="Screen Shot 2021-03-07 at 7 46 40 AM" src="https://user-images.githubusercontent.com/6684700/110246002-a770d900-7f1a-11eb-85fa-f294b61dd4bd.png">

**Comment by joshuarule** [comment]
@rationaledesign this isn't a bug. Maria took out the file for the document. When she puts it back it it will render out the download. Since there is an item in the downloads array the title is showing.
