### ISSUE TITLE
General – Footer Text Items

### ISSUE THREAD

**Issue by rationaledesign** [joshuarule/mainspringenergy.com#20]
Addl. items should be added to the Company column of the footer.

Should now be:
Newsroom
Company
Careers
Contact

**Comment by joshuarule** [comment]
@rationaledesign What is newsroom?

**Comment by rationaledesign** [comment]
Update for launch as follows:
<img width="195" alt="Screen Shot 2021-01-28 at 8 47 50 AM" src="https://user-images.githubusercontent.com/6684700/106238606-fd34c180-61b5-11eb-8ad1-d5501cd5705a.png">
