### ISSUE TITLE
Design – Add exec team photos

### ISSUE THREAD

**Issue by rationaledesign** [joshuarule/mainspringenergy.com#31]

**Comment by rationaledesign** [comment]
Think we are mostly covered here. BUT.... need to ensure that those that pop up are uncropped from a circle and in a rectangle.

**Comment by rationaledesign** [comment]
Also @joshuarule let's make sure we have Sully's final photoshopped images in the CMS too

**Comment by joshuarule** [comment]
@rationaledesign I'm not sure where to find these images.
