### ISSUE TITLE
P1 – Company Page investor logo section cleanup

### ISSUE THREAD

**Issue by rationaledesign** [joshuarule/mainspringenergy.com#34]

**Comment by rationaledesign** [comment]
![Uploading Screen Shot 2021-01-22 at 1.08.26 AM.png…]()

**Comment by rationaledesign** [comment]
Need to tweak visuals per example here @joshuarule 
<img width="1444" alt="Screen Shot 2021-01-22 at 1 08 26 AM" src="https://user-images.githubusercontent.com/6684700/105470431-649ac080-5c4e-11eb-92ce-4574f4188389.png">

Box background should be Ivory with a 1px Fog outline around each

**Comment by joshuarule** [comment]
@rationaledesign I assume you meant porcelain as the bg so I made it that.
