### ISSUE TITLE
Design – Customer Inquiries: required fields

### ISSUE THREAD

**Issue by rationaledesign** [joshuarule/mainspringenergy.com#48]

**Comment by joshuarule** [comment]
@rationaledesign not sure what this means. Feel free to expand and assign it to me

**Comment by joshuarule** [comment]
@rationaledesign need designs for how to handle this for first, last, email, company

**Comment by rationaledesign** [comment]
Also error states

**Comment by rationaledesign** [comment]
Sent design as new task to @joshuarule
